export {
  Zap as IconLightning,
  Radar as IconRadar,
  MapPin as IconPosition,
  Thermometer as IconMeteo,
  Siren as IconAllerte,
  Bot as IconCopilot,
  Crosshair as IconCell,
  Star as IconTarget,
  Wind as IconSpeed,
  RotateCw as IconSupercell,
  TrendingUp as IconTrendUp,
  TrendingDown as IconTrendDown,
  Minus as IconTrendSteady,
  Compass as IconRoute,
  MoveRight as IconDirect,
  Map as IconMap,
  Tornado as IconChase,
  Play as IconPlay,
  Pause as IconPause,
  Eye as IconVisible,
  EyeOff as IconHidden,
  Volume2 as IconSound,
  VolumeX as IconMuted,
  Mic as IconMic,
  MicOff as IconMicOff,
  X as IconClose,
  ChevronUp as IconExpand,
  ChevronDown as IconCollapse,
  ExternalLink as IconExternal,
  TriangleAlert as IconWarning,
  Circle as IconRec,
  ClipboardList as IconReport,
  History as IconHistory,
  Route as IconRoad,
  Gauge as IconGauge,
} from "lucide-react";

export function Logo({ className = "h-5 w-5" }: { className?: string }) {
  return <img src="/favicon.ico" alt="" aria-hidden className={`${className} shrink-0`} />;
}
